export type ItemCategory = "Furniture" | "Kitchen" | "Decor" | "Essentials";
export type ItemStatus = "available" | "reserved" | "unavailable";
export type ItemCondition = "Like New" | "Good" | "Fair";

export interface Property {
  id: string;
  name: string;
  address: string;
  neighborhood: string;
  type: string;
  moveOutDate: string;
  availableItemCount: number;
  thumbnail: string;
  description: string;
}

export interface Item {
  id: string;
  propertyId: string;
  name: string;
  category: ItemCategory;
  price: number;
  estimatedOriginalPrice?: number;
  condition: ItemCondition;
  status: ItemStatus;
  note: string;
  image: string;
}

// ---------------------------------------------------------------------------
// Properties
// ---------------------------------------------------------------------------

export const properties: Property[] = [
  {
    id: "prop-1",
    name: "140 Riverside Drive",
    address: "140 Riverside Dr, New York, NY 10024",
    neighborhood: "Morningside Heights",
    type: "Prewar Building",
    moveOutDate: "May 15, 2026",
    availableItemCount: 6,
    thumbnail: "🏛️",
    description:
      "Outgoing resident leaving after 4 years. Well-maintained items, most purchased in 2022. Open to bundling.",
  },
  {
    id: "prop-2",
    name: "45 Bedford Avenue",
    address: "45 Bedford Ave, Brooklyn, NY 11211",
    neighborhood: "Williamsburg",
    type: "Modern Rental",
    moveOutDate: "May 1, 2026",
    availableItemCount: 5,
    thumbnail: "🏢",
    description:
      "Young professional moving out of state. Mostly IKEA furniture in great condition — quick handoff preferred.",
  },
  {
    id: "prop-3",
    name: "23 Steinway Street",
    address: "23 Steinway St, Queens, NY 11103",
    neighborhood: "Astoria",
    type: "Walkup Apartment",
    moveOutDate: "April 30, 2026",
    availableItemCount: 4,
    thumbnail: "🏠",
    description:
      "Couple relocating overseas. Everything must go — very open to bundling items at a discount.",
  },
  {
    id: "prop-4",
    name: "88 Crown Street",
    address: "88 Crown St, Brooklyn, NY 11225",
    neighborhood: "Crown Heights",
    type: "Brownstone",
    moveOutDate: "May 20, 2026",
    availableItemCount: 6,
    thumbnail: "🏡",
    description:
      "Grad student finishing their program. Practical, well-priced items — priced to move quickly.",
  },
  {
    id: "prop-5",
    name: "200 Dyckman Street",
    address: "200 Dyckman St, New York, NY 10034",
    neighborhood: "Inwood",
    type: "High Rise",
    moveOutDate: "June 1, 2026",
    availableItemCount: 8,
    thumbnail: "🏬",
    description:
      "Family of 3 downsizing. Full kitchen set and furniture available. Flexible on pickup dates.",
  },
];

// ---------------------------------------------------------------------------
// Items
// ---------------------------------------------------------------------------

export const items: Item[] = [
  // ── prop-1 (Riverside Drive) ──────────────────────────────────────────────
  {
    id: "item-1",
    propertyId: "prop-1",
    name: "Standing Desk",
    category: "Furniture",
    price: 120,
    estimatedOriginalPrice: 350,
    condition: "Like New",
    status: "available",
    note: "Adjustable height, minor scratch on side panel. Includes cable tray.",
    image: "🖥️",
  },
  {
    id: "item-2",
    propertyId: "prop-1",
    name: "Ergonomic Office Chair",
    category: "Furniture",
    price: 80,
    estimatedOriginalPrice: 250,
    condition: "Good",
    status: "available",
    note: "Lumbar support, adjustable armrests. Some wear on the seat cushion.",
    image: "🪑",
  },
  {
    id: "item-3",
    propertyId: "prop-1",
    name: "Bookshelf (5-tier)",
    category: "Furniture",
    price: 45,
    estimatedOriginalPrice: 110,
    condition: "Good",
    status: "available",
    note: "KALLAX unit in white. Fits perfectly in a standard bedroom.",
    image: "📚",
  },
  {
    id: "item-4",
    propertyId: "prop-1",
    name: "Coffee Maker",
    category: "Kitchen",
    price: 30,
    estimatedOriginalPrice: 80,
    condition: "Good",
    status: "available",
    note: "12-cup Cuisinart. Descaled recently, works perfectly.",
    image: "☕",
  },
  {
    id: "item-5",
    propertyId: "prop-1",
    name: "Arc Floor Lamp",
    category: "Decor",
    price: 25,
    estimatedOriginalPrice: 60,
    condition: "Like New",
    status: "reserved",
    note: "Reserved — you can join the waitlist in your request.",
    image: "💡",
  },
  {
    id: "item-6",
    propertyId: "prop-1",
    name: "Dyson V7 Vacuum",
    category: "Essentials",
    price: 50,
    estimatedOriginalPrice: 150,
    condition: "Good",
    status: "available",
    note: "Battery holds about 20 minutes. All attachments included.",
    image: "🧹",
  },
  {
    id: "item-7",
    propertyId: "prop-1",
    name: "Full-Length Wall Mirror",
    category: "Decor",
    price: 35,
    estimatedOriginalPrice: 90,
    condition: "Like New",
    status: "available",
    note: "Leaning style, 65″ × 22″. No chips or cracks.",
    image: "🪞",
  },
  {
    id: "item-8",
    propertyId: "prop-1",
    name: "Bed Frame (Queen)",
    category: "Furniture",
    price: 90,
    estimatedOriginalPrice: 200,
    condition: "Good",
    status: "unavailable",
    note: "Already claimed by another resident.",
    image: "🛏️",
  },

  // ── prop-2 (Bedford Ave) ──────────────────────────────────────────────────
  {
    id: "item-9",
    propertyId: "prop-2",
    name: "EKTORP Sofa (2-seat)",
    category: "Furniture",
    price: 100,
    estimatedOriginalPrice: 400,
    condition: "Good",
    status: "available",
    note: "Light gray. Removable and washable covers. Very comfortable.",
    image: "🛋️",
  },
  {
    id: "item-10",
    propertyId: "prop-2",
    name: "Wood Dining Table",
    category: "Furniture",
    price: 75,
    estimatedOriginalPrice: 180,
    condition: "Good",
    status: "available",
    note: "Seats 4 comfortably. Minor scuffs on legs, top is clean.",
    image: "🍽️",
  },
  {
    id: "item-11",
    propertyId: "prop-2",
    name: "Toshiba Microwave",
    category: "Kitchen",
    price: 35,
    estimatedOriginalPrice: 90,
    condition: "Like New",
    status: "available",
    note: "900W. Bought 8 months ago — barely used.",
    image: "📦",
  },
  {
    id: "item-12",
    propertyId: "prop-2",
    name: "NutriBullet Blender",
    category: "Kitchen",
    price: 20,
    estimatedOriginalPrice: 60,
    condition: "Good",
    status: "available",
    note: "Pro model. Cups and blades all included.",
    image: "🥤",
  },
  {
    id: "item-13",
    propertyId: "prop-2",
    name: "Blackout Curtains (pair)",
    category: "Decor",
    price: 20,
    estimatedOriginalPrice: 55,
    condition: "Like New",
    status: "available",
    note: "Dark gray. Fits 60″ wide window. Rods not included.",
    image: "🪟",
  },
  {
    id: "item-14",
    propertyId: "prop-2",
    name: "Rowenta Steam Iron",
    category: "Essentials",
    price: 15,
    estimatedOriginalPrice: 45,
    condition: "Good",
    status: "reserved",
    note: "Reserved — join the waitlist in your request message.",
    image: "👔",
  },

  // ── prop-3 (Steinway St) ──────────────────────────────────────────────────
  {
    id: "item-15",
    propertyId: "prop-3",
    name: "Area Rug (5×8 ft)",
    category: "Decor",
    price: 60,
    estimatedOriginalPrice: 180,
    condition: "Good",
    status: "available",
    note: "Warm beige tones. Professionally cleaned before listing.",
    image: "🧶",
  },
  {
    id: "item-16",
    propertyId: "prop-3",
    name: "6-Drawer Dresser",
    category: "Furniture",
    price: 70,
    estimatedOriginalPrice: 200,
    condition: "Fair",
    status: "available",
    note: "Scratches on top surface. Drawers slide smoothly. Solid wood.",
    image: "🗄️",
  },
  {
    id: "item-17",
    propertyId: "prop-3",
    name: "Cuisinart Toaster Oven",
    category: "Kitchen",
    price: 25,
    estimatedOriginalPrice: 70,
    condition: "Good",
    status: "available",
    note: "6-slice capacity. Clean, works perfectly.",
    image: "🍞",
  },
  {
    id: "item-18",
    propertyId: "prop-3",
    name: "Nightstand",
    category: "Furniture",
    price: 20,
    estimatedOriginalPrice: 60,
    condition: "Fair",
    status: "available",
    note: "One drawer + small shelf. Small chip on one corner.",
    image: "🪵",
  },
  {
    id: "item-19",
    propertyId: "prop-3",
    name: "Foldable Ironing Board",
    category: "Essentials",
    price: 10,
    estimatedOriginalPrice: 35,
    condition: "Fair",
    status: "unavailable",
    note: "Already claimed.",
    image: "🧺",
  },

  // ── prop-4 (Crown Street) ─────────────────────────────────────────────────
  {
    id: "item-20",
    propertyId: "prop-4",
    name: "Round Coffee Table",
    category: "Furniture",
    price: 40,
    estimatedOriginalPrice: 120,
    condition: "Good",
    status: "available",
    note: "Wood top, hairpin legs. Fits most living room setups.",
    image: "🪵",
  },
  {
    id: "item-21",
    propertyId: "prop-4",
    name: "LED Desk Lamp",
    category: "Decor",
    price: 15,
    estimatedOriginalPrice: 40,
    condition: "Like New",
    status: "available",
    note: "Adjustable neck. USB-A charging port on base. Barely used.",
    image: "🔦",
  },
  {
    id: "item-22",
    propertyId: "prop-4",
    name: "Non-Stick Pot & Pan Set",
    category: "Kitchen",
    price: 40,
    estimatedOriginalPrice: 120,
    condition: "Good",
    status: "available",
    note: "8-piece set. Minor scratches inside one pan from utensil use.",
    image: "🍳",
  },
  {
    id: "item-23",
    propertyId: "prop-4",
    name: "Storage Ottoman",
    category: "Furniture",
    price: 30,
    estimatedOriginalPrice: 75,
    condition: "Good",
    status: "available",
    note: "Hidden storage inside. Gray fabric, no visible stains.",
    image: "📦",
  },
  {
    id: "item-24",
    propertyId: "prop-4",
    name: "Full-Size Drying Rack",
    category: "Essentials",
    price: 10,
    estimatedOriginalPrice: 25,
    condition: "Fair",
    status: "available",
    note: "Foldable. Slight rust on two lower bars, otherwise functional.",
    image: "🧺",
  },
  {
    id: "item-25",
    propertyId: "prop-4",
    name: "Chunky Knit Throw",
    category: "Decor",
    price: 15,
    estimatedOriginalPrice: 40,
    condition: "Like New",
    status: "available",
    note: "Cream color. Washed and folded. Super cozy.",
    image: "🛋️",
  },
  {
    id: "item-26",
    propertyId: "prop-4",
    name: "3-Tier Bookshelf",
    category: "Furniture",
    price: 25,
    estimatedOriginalPrice: 65,
    condition: "Fair",
    status: "reserved",
    note: "One request in — not confirmed. Mention your interest.",
    image: "📚",
  },

  // ── prop-5 (Dyckman St) ───────────────────────────────────────────────────
  {
    id: "item-27",
    propertyId: "prop-5",
    name: "Dining Chairs × 4",
    category: "Furniture",
    price: 80,
    estimatedOriginalPrice: 240,
    condition: "Good",
    status: "available",
    note: "Sold as a set. Mid-century wood style with padded seats.",
    image: "🪑",
  },
  {
    id: "item-28",
    propertyId: "prop-5",
    name: "Zojirushi Rice Cooker",
    category: "Kitchen",
    price: 25,
    estimatedOriginalPrice: 70,
    condition: "Like New",
    status: "available",
    note: "3-cup model. Barely used — in perfect condition.",
    image: "🍚",
  },
  {
    id: "item-29",
    propertyId: "prop-5",
    name: "Large Bookcase (6-tier)",
    category: "Furniture",
    price: 60,
    estimatedOriginalPrice: 160,
    condition: "Good",
    status: "available",
    note: "White finish. Fills a full wall nicely.",
    image: "📚",
  },
  {
    id: "item-30",
    propertyId: "prop-5",
    name: "Silent Wall Clock",
    category: "Decor",
    price: 12,
    estimatedOriginalPrice: 30,
    condition: "Like New",
    status: "available",
    note: "Sweep mechanism — no ticking. Batteries included.",
    image: "🕐",
  },
  {
    id: "item-31",
    propertyId: "prop-5",
    name: "Levoit Air Purifier",
    category: "Essentials",
    price: 55,
    estimatedOriginalPrice: 150,
    condition: "Good",
    status: "available",
    note: "Core 300 model. Filter replaced 3 months ago.",
    image: "💨",
  },
  {
    id: "item-32",
    propertyId: "prop-5",
    name: "Oval Bathroom Mirror",
    category: "Decor",
    price: 20,
    estimatedOriginalPrice: 55,
    condition: "Like New",
    status: "available",
    note: "24″ × 36″. No chips or cracks. Easy to hang.",
    image: "🪞",
  },
  {
    id: "item-33",
    propertyId: "prop-5",
    name: "Velvet Hangers (50-pack)",
    category: "Essentials",
    price: 8,
    estimatedOriginalPrice: 20,
    condition: "Like New",
    status: "available",
    note: "Slim profile. Still in original packaging.",
    image: "👚",
  },
  {
    id: "item-34",
    propertyId: "prop-5",
    name: "TV Stand (up to 60″)",
    category: "Furniture",
    price: 55,
    estimatedOriginalPrice: 140,
    condition: "Good",
    status: "reserved",
    note: "Reserved — waitlist open. Mention interest in your message.",
    image: "📺",
  },
  {
    id: "item-35",
    propertyId: "prop-5",
    name: "Digital Kitchen Scale",
    category: "Kitchen",
    price: 10,
    estimatedOriginalPrice: 25,
    condition: "Like New",
    status: "available",
    note: "Up to 11 lbs. Batteries included. Pristine condition.",
    image: "⚖️",
  },
];
